<?php
$data = array (
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '生鲜食品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '1',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '2',
    'name' => '生鲜食品',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '粮油调味',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '5',
    'name' => '粮油调味',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '食用油',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 2,
    'id' => '30',
    'name' => '食用油',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '方便速食',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '34',
    'name' => '方便速食',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '米面杂粮',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '31',
    'name' => '米面杂粮',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '厨房调料',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '32',
    'name' => '厨房调料',
  ),
  170 => 
  array (
    'cat_id' => '170',
    'cat_name' => '牛乳制品',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '170',
    'name' => '牛乳制品',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '瓜果蔬菜',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '18',
    'name' => '瓜果蔬菜',
  ),
  174 => 
  array (
    'cat_id' => '174',
    'cat_name' => '四季鲜果',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '174',
    'name' => '四季鲜果',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => '时令鲜蔬',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '77',
    'name' => '时令鲜蔬',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '海鲜水产',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '16',
    'name' => '海鲜水产',
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => '鱼',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '69',
    'name' => '鱼',
  ),
  70 => 
  array (
    'cat_id' => '70',
    'cat_name' => '虾',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '70',
    'name' => '虾',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => '蟹/贝',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '71',
    'name' => '蟹/贝',
  ),
  68 => 
  array (
    'cat_id' => '68',
    'cat_name' => '参鲍',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '68',
    'name' => '参鲍',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '精品肉类',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => '8',
    'level' => 1,
    'id' => '15',
    'name' => '精品肉类',
  ),
  65 => 
  array (
    'cat_id' => '65',
    'cat_name' => '禽类',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '65',
    'name' => '禽类',
  ),
  66 => 
  array (
    'cat_id' => '66',
    'cat_name' => '猪肉',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '66',
    'name' => '猪肉',
  ),
  67 => 
  array (
    'cat_id' => '67',
    'cat_name' => '牛肉',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '67',
    'name' => '牛肉',
  ),
  64 => 
  array (
    'cat_id' => '64',
    'cat_name' => '羊肉',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '64',
    'name' => '羊肉',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '酒水饮品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '酒水饮品',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '茗茶',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '7',
    'name' => '茗茶',
  ),
  62 => 
  array (
    'cat_id' => '62',
    'cat_name' => '红茶',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '62',
    'name' => '红茶',
  ),
  63 => 
  array (
    'cat_id' => '63',
    'cat_name' => '绿茶',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '63',
    'name' => '绿茶',
  ),
  138 => 
  array (
    'cat_id' => '138',
    'cat_name' => '乌龙茶',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '138',
    'name' => '乌龙茶',
  ),
  61 => 
  array (
    'cat_id' => '61',
    'cat_name' => '白茶',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '61',
    'name' => '白茶',
  ),
  137 => 
  array (
    'cat_id' => '137',
    'cat_name' => '黑茶',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '137',
    'name' => '黑茶',
  ),
  145 => 
  array (
    'cat_id' => '145',
    'cat_name' => '咖啡',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '145',
    'name' => '咖啡',
  ),
  164 => 
  array (
    'cat_id' => '164',
    'cat_name' => '速溶咖啡',
    'measure_unit' => '',
    'parent_id' => '145',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '164',
    'name' => '速溶咖啡',
  ),
  165 => 
  array (
    'cat_id' => '165',
    'cat_name' => '咖啡粉',
    'measure_unit' => '',
    'parent_id' => '145',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '165',
    'name' => '咖啡粉',
  ),
  166 => 
  array (
    'cat_id' => '166',
    'cat_name' => '咖啡豆',
    'measure_unit' => '',
    'parent_id' => '145',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '166',
    'name' => '咖啡豆',
  ),
  146 => 
  array (
    'cat_id' => '146',
    'cat_name' => '饮料',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '146',
    'name' => '饮料',
  ),
  167 => 
  array (
    'cat_id' => '167',
    'cat_name' => '矿泉水',
    'measure_unit' => '',
    'parent_id' => '146',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '167',
    'name' => '矿泉水',
  ),
  168 => 
  array (
    'cat_id' => '168',
    'cat_name' => '碳酸饮料',
    'measure_unit' => '',
    'parent_id' => '146',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '168',
    'name' => '碳酸饮料',
  ),
  169 => 
  array (
    'cat_id' => '169',
    'cat_name' => '果汁',
    'measure_unit' => '',
    'parent_id' => '146',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '169',
    'name' => '果汁',
  ),
  144 => 
  array (
    'cat_id' => '144',
    'cat_name' => '美酒',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '144',
    'name' => '美酒',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '白酒',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '2',
    'goods_num' => '7',
    'level' => 2,
    'id' => '23',
    'name' => '白酒',
  ),
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => '茅台',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '85',
    'name' => '茅台',
  ),
  83 => 
  array (
    'cat_id' => '83',
    'cat_name' => '五粮液',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '83',
    'name' => '五粮液',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '啤酒',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '26',
    'name' => '啤酒',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '葡萄酒',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '24',
    'name' => '葡萄酒',
  ),
  162 => 
  array (
    'cat_id' => '162',
    'cat_name' => '黄酒',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '162',
    'name' => '黄酒',
  ),
  163 => 
  array (
    'cat_id' => '163',
    'cat_name' => '保健酒',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '163',
    'name' => '保健酒',
  ),
  132 => 
  array (
    'cat_id' => '132',
    'cat_name' => '美妆洗化',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '132',
    'name' => '美妆洗化',
  ),
  159 => 
  array (
    'cat_id' => '159',
    'cat_name' => '洗发护发',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '159',
    'name' => '洗发护发',
  ),
  161 => 
  array (
    'cat_id' => '161',
    'cat_name' => '护发素',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '161',
    'name' => '护发素',
  ),
  160 => 
  array (
    'cat_id' => '160',
    'cat_name' => '洗发水',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '15',
    'level' => 2,
    'id' => '160',
    'name' => '洗发水',
  ),
  140 => 
  array (
    'cat_id' => '140',
    'cat_name' => '面部护理',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '140',
    'name' => '面部护理',
  ),
  151 => 
  array (
    'cat_id' => '151',
    'cat_name' => '香皂',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 2,
    'id' => '151',
    'name' => '香皂',
  ),
  152 => 
  array (
    'cat_id' => '152',
    'cat_name' => '洁面乳',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '152',
    'name' => '洁面乳',
  ),
  153 => 
  array (
    'cat_id' => '153',
    'cat_name' => '面膜',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '153',
    'name' => '面膜',
  ),
  139 => 
  array (
    'cat_id' => '139',
    'cat_name' => '口腔护理',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '139',
    'name' => '口腔护理',
  ),
  148 => 
  array (
    'cat_id' => '148',
    'cat_name' => '牙刷',
    'measure_unit' => '',
    'parent_id' => '139',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '148',
    'name' => '牙刷',
  ),
  149 => 
  array (
    'cat_id' => '149',
    'cat_name' => '漱口水',
    'measure_unit' => '',
    'parent_id' => '139',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '149',
    'name' => '漱口水',
  ),
  150 => 
  array (
    'cat_id' => '150',
    'cat_name' => '牙线',
    'measure_unit' => '',
    'parent_id' => '139',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '150',
    'name' => '牙线',
  ),
  147 => 
  array (
    'cat_id' => '147',
    'cat_name' => '牙膏',
    'measure_unit' => '',
    'parent_id' => '139',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '15',
    'level' => 2,
    'id' => '147',
    'name' => '牙膏',
  ),
  182 => 
  array (
    'cat_id' => '182',
    'cat_name' => '厨卫清洁',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '182',
    'name' => '厨卫清洁',
  ),
  183 => 
  array (
    'cat_id' => '183',
    'cat_name' => '洗洁精',
    'measure_unit' => '',
    'parent_id' => '182',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '183',
    'name' => '洗洁精',
  ),
  184 => 
  array (
    'cat_id' => '184',
    'cat_name' => '洁厕灵',
    'measure_unit' => '',
    'parent_id' => '182',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '184',
    'name' => '洁厕灵',
  ),
  171 => 
  array (
    'cat_id' => '171',
    'cat_name' => '沐浴清洁',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '171',
    'name' => '沐浴清洁',
  ),
  180 => 
  array (
    'cat_id' => '180',
    'cat_name' => '洗手液',
    'measure_unit' => '',
    'parent_id' => '171',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '180',
    'name' => '洗手液',
  ),
  179 => 
  array (
    'cat_id' => '179',
    'cat_name' => '沐浴露',
    'measure_unit' => '',
    'parent_id' => '171',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '179',
    'name' => '沐浴露',
  ),
  141 => 
  array (
    'cat_id' => '141',
    'cat_name' => '衣物清洁',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '141',
    'name' => '衣物清洁',
  ),
  154 => 
  array (
    'cat_id' => '154',
    'cat_name' => '洗衣液',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '154',
    'name' => '洗衣液',
  ),
  186 => 
  array (
    'cat_id' => '186',
    'cat_name' => '洗衣皂',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 2,
    'id' => '186',
    'name' => '洗衣皂',
  ),
  158 => 
  array (
    'cat_id' => '158',
    'cat_name' => '透明皂',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '158',
    'name' => '透明皂',
  ),
  155 => 
  array (
    'cat_id' => '155',
    'cat_name' => '洗衣粉',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 2,
    'id' => '155',
    'name' => '洗衣粉',
  ),
  181 => 
  array (
    'cat_id' => '181',
    'cat_name' => '柔顺剂',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '181',
    'name' => '柔顺剂',
  ),
  156 => 
  array (
    'cat_id' => '156',
    'cat_name' => '内衣皂',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '156',
    'name' => '内衣皂',
  ),
  157 => 
  array (
    'cat_id' => '157',
    'cat_name' => '天然皂粉',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '157',
    'name' => '天然皂粉',
  ),
  133 => 
  array (
    'cat_id' => '133',
    'cat_name' => '家居家纺',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '133',
    'name' => '家居家纺',
  ),
  134 => 
  array (
    'cat_id' => '134',
    'cat_name' => '箱包钟表',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '134',
    'name' => '箱包钟表',
  ),
  136 => 
  array (
    'cat_id' => '136',
    'cat_name' => '汽车用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '136',
    'name' => '汽车用品',
  ),
  142 => 
  array (
    'cat_id' => '142',
    'cat_name' => '润滑油',
    'measure_unit' => '',
    'parent_id' => '136',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '142',
    'name' => '润滑油',
  ),
  135 => 
  array (
    'cat_id' => '135',
    'cat_name' => '家用电器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '135',
    'name' => '家用电器',
  ),
  172 => 
  array (
    'cat_id' => '172',
    'cat_name' => '户外运动',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '172',
    'name' => '户外运动',
  ),
  173 => 
  array (
    'cat_id' => '173',
    'cat_name' => '时装鞋靴',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '173',
    'name' => '时装鞋靴',
  ),
  175 => 
  array (
    'cat_id' => '175',
    'cat_name' => '女装',
    'measure_unit' => '',
    'parent_id' => '173',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '175',
    'name' => '女装',
  ),
  187 => 
  array (
    'cat_id' => '187',
    'cat_name' => '貂皮大衣',
    'measure_unit' => '',
    'parent_id' => '175',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '187',
    'name' => '貂皮大衣',
  ),
  177 => 
  array (
    'cat_id' => '177',
    'cat_name' => '男鞋',
    'measure_unit' => '',
    'parent_id' => '173',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '177',
    'name' => '男鞋',
  ),
  176 => 
  array (
    'cat_id' => '176',
    'cat_name' => '男装',
    'measure_unit' => '',
    'parent_id' => '173',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '176',
    'name' => '男装',
  ),
  188 => 
  array (
    'cat_id' => '188',
    'cat_name' => '貂皮大衣',
    'measure_unit' => '',
    'parent_id' => '176',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '188',
    'name' => '貂皮大衣',
  ),
  178 => 
  array (
    'cat_id' => '178',
    'cat_name' => '女鞋',
    'measure_unit' => '',
    'parent_id' => '173',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '178',
    'name' => '女鞋',
  ),
  143 => 
  array (
    'cat_id' => '143',
    'cat_name' => '直销产品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '15',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '143',
    'name' => '直销产品',
  ),
  131 => 
  array (
    'cat_id' => '131',
    'cat_name' => '临时分类',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '55',
    'level' => 0,
    'id' => '131',
    'name' => '临时分类',
  ),
);
?>