<?php
$data = array (
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '粮油食品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '1',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '2',
    'name' => '粮油食品',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '粮油调味',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '5',
    'name' => '粮油调味',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '厨房调料',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 2,
    'id' => '32',
    'name' => '厨房调料',
  ),
  200 => 
  array (
    'cat_id' => '200',
    'cat_name' => '巧媳妇',
    'measure_unit' => '',
    'parent_id' => '32',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 3,
    'id' => '200',
    'name' => '巧媳妇',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '食用油',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '21',
    'level' => 2,
    'id' => '30',
    'name' => '食用油',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '方便速食',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '34',
    'name' => '方便速食',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '米面杂粮',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 2,
    'id' => '31',
    'name' => '米面杂粮',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '海鲜水产',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '16',
    'name' => '海鲜水产',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => '蟹/贝',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '71',
    'name' => '蟹/贝',
  ),
  68 => 
  array (
    'cat_id' => '68',
    'cat_name' => '参鲍',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '68',
    'name' => '参鲍',
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => '鱼',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '69',
    'name' => '鱼',
  ),
  70 => 
  array (
    'cat_id' => '70',
    'cat_name' => '虾',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '70',
    'name' => '虾',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '精品肉类',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '15',
    'name' => '精品肉类',
  ),
  67 => 
  array (
    'cat_id' => '67',
    'cat_name' => '牛肉',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '67',
    'name' => '牛肉',
  ),
  64 => 
  array (
    'cat_id' => '64',
    'cat_name' => '羊肉',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '64',
    'name' => '羊肉',
  ),
  65 => 
  array (
    'cat_id' => '65',
    'cat_name' => '禽类',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '65',
    'name' => '禽类',
  ),
  66 => 
  array (
    'cat_id' => '66',
    'cat_name' => '猪肉',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '66',
    'name' => '猪肉',
  ),
  170 => 
  array (
    'cat_id' => '170',
    'cat_name' => '牛乳制品',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '170',
    'name' => '牛乳制品',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '瓜果蔬菜',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '18',
    'name' => '瓜果蔬菜',
  ),
  174 => 
  array (
    'cat_id' => '174',
    'cat_name' => '四季鲜果',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '174',
    'name' => '四季鲜果',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => '时令鲜蔬',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '77',
    'name' => '时令鲜蔬',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '烟酒茶饮',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '烟酒茶饮',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '茗茶',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '7',
    'name' => '茗茶',
  ),
  61 => 
  array (
    'cat_id' => '61',
    'cat_name' => '白茶',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '61',
    'name' => '白茶',
  ),
  137 => 
  array (
    'cat_id' => '137',
    'cat_name' => '黑茶',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '137',
    'name' => '黑茶',
  ),
  62 => 
  array (
    'cat_id' => '62',
    'cat_name' => '红茶',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '62',
    'name' => '红茶',
  ),
  63 => 
  array (
    'cat_id' => '63',
    'cat_name' => '绿茶',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '63',
    'name' => '绿茶',
  ),
  138 => 
  array (
    'cat_id' => '138',
    'cat_name' => '乌龙茶',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '21',
    'level' => 2,
    'id' => '138',
    'name' => '乌龙茶',
  ),
  144 => 
  array (
    'cat_id' => '144',
    'cat_name' => '美酒',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '144',
    'name' => '美酒',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '白酒',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '34',
    'level' => 2,
    'id' => '23',
    'name' => '白酒',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '啤酒',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '26',
    'name' => '啤酒',
  ),
  163 => 
  array (
    'cat_id' => '163',
    'cat_name' => '保健酒',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '163',
    'name' => '保健酒',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '葡萄酒',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '24',
    'name' => '葡萄酒',
  ),
  162 => 
  array (
    'cat_id' => '162',
    'cat_name' => '黄酒',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '162',
    'name' => '黄酒',
  ),
  191 => 
  array (
    'cat_id' => '191',
    'cat_name' => '香烟',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '191',
    'name' => '香烟',
  ),
  146 => 
  array (
    'cat_id' => '146',
    'cat_name' => '饮料',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '146',
    'name' => '饮料',
  ),
  168 => 
  array (
    'cat_id' => '168',
    'cat_name' => '碳酸饮料',
    'measure_unit' => '',
    'parent_id' => '146',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '168',
    'name' => '碳酸饮料',
  ),
  169 => 
  array (
    'cat_id' => '169',
    'cat_name' => '果汁',
    'measure_unit' => '',
    'parent_id' => '146',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '169',
    'name' => '果汁',
  ),
  167 => 
  array (
    'cat_id' => '167',
    'cat_name' => '矿泉水',
    'measure_unit' => '',
    'parent_id' => '146',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '167',
    'name' => '矿泉水',
  ),
  132 => 
  array (
    'cat_id' => '132',
    'cat_name' => '美妆洗化',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '10',
    'goods_num' => 3,
    'level' => 0,
    'id' => '132',
    'name' => '美妆洗化',
  ),
  213 => 
  array (
    'cat_id' => '213',
    'cat_name' => '相宜本草',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => '20',
    'level' => 1,
    'id' => '213',
    'name' => '相宜本草',
  ),
  217 => 
  array (
    'cat_id' => '217',
    'cat_name' => '相宜本草四倍系列',
    'measure_unit' => '',
    'parent_id' => '213',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
    'level' => 2,
    'id' => '217',
    'name' => '相宜本草四倍系列',
  ),
  214 => 
  array (
    'cat_id' => '214',
    'cat_name' => '百合高保湿系列',
    'measure_unit' => '',
    'parent_id' => '213',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 2,
    'id' => '214',
    'name' => '百合高保湿系列',
  ),
  215 => 
  array (
    'cat_id' => '215',
    'cat_name' => '芯净自然系列',
    'measure_unit' => '',
    'parent_id' => '213',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 2,
    'id' => '215',
    'name' => '芯净自然系列',
  ),
  216 => 
  array (
    'cat_id' => '216',
    'cat_name' => '红景系列',
    'measure_unit' => '',
    'parent_id' => '213',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '21',
    'level' => 2,
    'id' => '216',
    'name' => '红景系列',
  ),
  140 => 
  array (
    'cat_id' => '140',
    'cat_name' => '面部护理',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => '26',
    'level' => 1,
    'id' => '140',
    'name' => '面部护理',
  ),
  153 => 
  array (
    'cat_id' => '153',
    'cat_name' => '面膜',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '153',
    'name' => '面膜',
  ),
  152 => 
  array (
    'cat_id' => '152',
    'cat_name' => '洁面乳',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '152',
    'name' => '洁面乳',
  ),
  139 => 
  array (
    'cat_id' => '139',
    'cat_name' => '口腔护理',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '139',
    'name' => '口腔护理',
  ),
  150 => 
  array (
    'cat_id' => '150',
    'cat_name' => '牙线',
    'measure_unit' => '',
    'parent_id' => '139',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '150',
    'name' => '牙线',
  ),
  147 => 
  array (
    'cat_id' => '147',
    'cat_name' => '牙膏',
    'measure_unit' => '',
    'parent_id' => '139',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => '31',
    'level' => 2,
    'id' => '147',
    'name' => '牙膏',
  ),
  212 => 
  array (
    'cat_id' => '212',
    'cat_name' => 'Colgate高露洁',
    'measure_unit' => '',
    'parent_id' => '147',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '19',
    'level' => 3,
    'id' => '212',
    'name' => 'Colgate高露洁',
  ),
  148 => 
  array (
    'cat_id' => '148',
    'cat_name' => '牙刷',
    'measure_unit' => '',
    'parent_id' => '139',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '46',
    'level' => 2,
    'id' => '148',
    'name' => '牙刷',
  ),
  149 => 
  array (
    'cat_id' => '149',
    'cat_name' => '漱口水',
    'measure_unit' => '',
    'parent_id' => '139',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '149',
    'name' => '漱口水',
  ),
  204 => 
  array (
    'cat_id' => '204',
    'cat_name' => '美妆日用',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '15',
    'level' => 1,
    'id' => '204',
    'name' => '美妆日用',
  ),
  182 => 
  array (
    'cat_id' => '182',
    'cat_name' => '厨卫清洁',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => '14',
    'level' => 1,
    'id' => '182',
    'name' => '厨卫清洁',
  ),
  189 => 
  array (
    'cat_id' => '189',
    'cat_name' => '机用清洁剂',
    'measure_unit' => '',
    'parent_id' => '182',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => '2',
    'level' => 2,
    'id' => '189',
    'name' => '机用清洁剂',
  ),
  190 => 
  array (
    'cat_id' => '190',
    'cat_name' => '水管疏通剂',
    'measure_unit' => '',
    'parent_id' => '189',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 3,
    'id' => '190',
    'name' => '水管疏通剂',
  ),
  183 => 
  array (
    'cat_id' => '183',
    'cat_name' => '洗洁精',
    'measure_unit' => '',
    'parent_id' => '182',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '183',
    'name' => '洗洁精',
  ),
  184 => 
  array (
    'cat_id' => '184',
    'cat_name' => '洁厕灵',
    'measure_unit' => '',
    'parent_id' => '182',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
    'level' => 2,
    'id' => '184',
    'name' => '洁厕灵',
  ),
  171 => 
  array (
    'cat_id' => '171',
    'cat_name' => '沐浴清洁',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => '6',
    'level' => 1,
    'id' => '171',
    'name' => '沐浴清洁',
  ),
  179 => 
  array (
    'cat_id' => '179',
    'cat_name' => '沐浴露',
    'measure_unit' => '',
    'parent_id' => '171',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '12',
    'level' => 2,
    'id' => '179',
    'name' => '沐浴露',
  ),
  151 => 
  array (
    'cat_id' => '151',
    'cat_name' => '香皂',
    'measure_unit' => '',
    'parent_id' => '171',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 2,
    'id' => '151',
    'name' => '香皂',
  ),
  180 => 
  array (
    'cat_id' => '180',
    'cat_name' => '洗手液',
    'measure_unit' => '',
    'parent_id' => '171',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '180',
    'name' => '洗手液',
  ),
  141 => 
  array (
    'cat_id' => '141',
    'cat_name' => '衣物清洁',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '141',
    'name' => '衣物清洁',
  ),
  156 => 
  array (
    'cat_id' => '156',
    'cat_name' => '内衣皂',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '156',
    'name' => '内衣皂',
  ),
  157 => 
  array (
    'cat_id' => '157',
    'cat_name' => '天然皂粉',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '157',
    'name' => '天然皂粉',
  ),
  154 => 
  array (
    'cat_id' => '154',
    'cat_name' => '洗衣液',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '154',
    'name' => '洗衣液',
  ),
  186 => 
  array (
    'cat_id' => '186',
    'cat_name' => '洗衣皂',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 2,
    'id' => '186',
    'name' => '洗衣皂',
  ),
  158 => 
  array (
    'cat_id' => '158',
    'cat_name' => '透明皂',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '158',
    'name' => '透明皂',
  ),
  155 => 
  array (
    'cat_id' => '155',
    'cat_name' => '洗衣粉',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 2,
    'id' => '155',
    'name' => '洗衣粉',
  ),
  181 => 
  array (
    'cat_id' => '181',
    'cat_name' => '柔顺剂',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '181',
    'name' => '柔顺剂',
  ),
  202 => 
  array (
    'cat_id' => '202',
    'cat_name' => '韩束专区',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => '11',
    'level' => 1,
    'id' => '202',
    'name' => '韩束专区',
  ),
  210 => 
  array (
    'cat_id' => '210',
    'cat_name' => '洁面乳',
    'measure_unit' => '',
    'parent_id' => '202',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
    'level' => 2,
    'id' => '210',
    'name' => '洁面乳',
  ),
  207 => 
  array (
    'cat_id' => '207',
    'cat_name' => '补水系列',
    'measure_unit' => '',
    'parent_id' => '202',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
    'level' => 2,
    'id' => '207',
    'name' => '补水系列',
  ),
  211 => 
  array (
    'cat_id' => '211',
    'cat_name' => '韩束套装',
    'measure_unit' => '',
    'parent_id' => '202',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 2,
    'id' => '211',
    'name' => '韩束套装',
  ),
  205 => 
  array (
    'cat_id' => '205',
    'cat_name' => '面部清洁',
    'measure_unit' => '',
    'parent_id' => '202',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
    'level' => 2,
    'id' => '205',
    'name' => '面部清洁',
  ),
  218 => 
  array (
    'cat_id' => '218',
    'cat_name' => '红景天系列',
    'measure_unit' => '',
    'parent_id' => '202',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '218',
    'name' => '红景天系列',
  ),
  209 => 
  array (
    'cat_id' => '209',
    'cat_name' => '韩束细肤',
    'measure_unit' => '',
    'parent_id' => '202',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '209',
    'name' => '韩束细肤',
  ),
  206 => 
  array (
    'cat_id' => '206',
    'cat_name' => '凝乳',
    'measure_unit' => '',
    'parent_id' => '202',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '206',
    'name' => '凝乳',
  ),
  203 => 
  array (
    'cat_id' => '203',
    'cat_name' => '弹润系列',
    'measure_unit' => '',
    'parent_id' => '202',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 2,
    'id' => '203',
    'name' => '弹润系列',
  ),
  199 => 
  array (
    'cat_id' => '199',
    'cat_name' => '儿童护理',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => '6',
    'level' => 1,
    'id' => '199',
    'name' => '儿童护理',
  ),
  201 => 
  array (
    'cat_id' => '201',
    'cat_name' => '青蛙王子',
    'measure_unit' => '',
    'parent_id' => '199',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '14',
    'level' => 2,
    'id' => '201',
    'name' => '青蛙王子',
  ),
  159 => 
  array (
    'cat_id' => '159',
    'cat_name' => '洗发护发',
    'measure_unit' => '',
    'parent_id' => '132',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => '3',
    'level' => 1,
    'id' => '159',
    'name' => '洗发护发',
  ),
  160 => 
  array (
    'cat_id' => '160',
    'cat_name' => '洗发水',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '41',
    'level' => 2,
    'id' => '160',
    'name' => '洗发水',
  ),
  161 => 
  array (
    'cat_id' => '161',
    'cat_name' => '护发素',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 2,
    'id' => '161',
    'name' => '护发素',
  ),
  133 => 
  array (
    'cat_id' => '133',
    'cat_name' => '家居家纺',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '5',
    'goods_num' => '7',
    'level' => 0,
    'id' => '133',
    'name' => '家居家纺',
  ),
  194 => 
  array (
    'cat_id' => '194',
    'cat_name' => '十件套',
    'measure_unit' => '',
    'parent_id' => '133',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '194',
    'name' => '十件套',
  ),
  195 => 
  array (
    'cat_id' => '195',
    'cat_name' => '被子',
    'measure_unit' => '',
    'parent_id' => '133',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '195',
    'name' => '被子',
  ),
  193 => 
  array (
    'cat_id' => '193',
    'cat_name' => '六件套',
    'measure_unit' => '',
    'parent_id' => '133',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '193',
    'name' => '六件套',
  ),
  196 => 
  array (
    'cat_id' => '196',
    'cat_name' => '毯子',
    'measure_unit' => '',
    'parent_id' => '133',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '196',
    'name' => '毯子',
  ),
  192 => 
  array (
    'cat_id' => '192',
    'cat_name' => '四件套',
    'measure_unit' => '',
    'parent_id' => '133',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '192',
    'name' => '四件套',
  ),
  134 => 
  array (
    'cat_id' => '134',
    'cat_name' => '箱包钟表',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '134',
    'name' => '箱包钟表',
  ),
  136 => 
  array (
    'cat_id' => '136',
    'cat_name' => '汽车用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '136',
    'name' => '汽车用品',
  ),
  142 => 
  array (
    'cat_id' => '142',
    'cat_name' => '润滑油',
    'measure_unit' => '',
    'parent_id' => '136',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '142',
    'name' => '润滑油',
  ),
  135 => 
  array (
    'cat_id' => '135',
    'cat_name' => '数码电器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '135',
    'name' => '数码电器',
  ),
  197 => 
  array (
    'cat_id' => '197',
    'cat_name' => '抽油烟机',
    'measure_unit' => '',
    'parent_id' => '135',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '197',
    'name' => '抽油烟机',
  ),
  198 => 
  array (
    'cat_id' => '198',
    'cat_name' => '燃气灶',
    'measure_unit' => '',
    'parent_id' => '135',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '198',
    'name' => '燃气灶',
  ),
  172 => 
  array (
    'cat_id' => '172',
    'cat_name' => '户外运动',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '172',
    'name' => '户外运动',
  ),
  173 => 
  array (
    'cat_id' => '173',
    'cat_name' => '时装鞋靴',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '173',
    'name' => '时装鞋靴',
  ),
  175 => 
  array (
    'cat_id' => '175',
    'cat_name' => '女装',
    'measure_unit' => '',
    'parent_id' => '173',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '175',
    'name' => '女装',
  ),
  187 => 
  array (
    'cat_id' => '187',
    'cat_name' => '貂皮大衣',
    'measure_unit' => '',
    'parent_id' => '175',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '187',
    'name' => '貂皮大衣',
  ),
  177 => 
  array (
    'cat_id' => '177',
    'cat_name' => '男鞋',
    'measure_unit' => '',
    'parent_id' => '173',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '177',
    'name' => '男鞋',
  ),
  176 => 
  array (
    'cat_id' => '176',
    'cat_name' => '男装',
    'measure_unit' => '',
    'parent_id' => '173',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '176',
    'name' => '男装',
  ),
  188 => 
  array (
    'cat_id' => '188',
    'cat_name' => '貂皮大衣',
    'measure_unit' => '',
    'parent_id' => '176',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '188',
    'name' => '貂皮大衣',
  ),
  178 => 
  array (
    'cat_id' => '178',
    'cat_name' => '女鞋',
    'measure_unit' => '',
    'parent_id' => '173',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '178',
    'name' => '女鞋',
  ),
  143 => 
  array (
    'cat_id' => '143',
    'cat_name' => '直销产品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '15',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '143',
    'name' => '直销产品',
  ),
  131 => 
  array (
    'cat_id' => '131',
    'cat_name' => '临时分类',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '55',
    'level' => 0,
    'id' => '131',
    'name' => '临时分类',
  ),
  208 => 
  array (
    'cat_id' => '208',
    'cat_name' => '大礼包',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '208',
    'name' => '大礼包',
  ),
);
?>